domain: shrey27tri01.github.io
url: https://shrey27tri01.github.io
source:      .
destination: ./_site
includes:    ./_includes
baseurl: 
google_analytics: G-RC7VSHBTX6

collections:
  projects:
    output: true
